forge "http://forge.puppetlabs.com"

# mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'

mod 'grahamgilbert/mac_admin'
mod 'grahamgilbert/mac_facts'
mod 'rcoleman/mac_profiles_handler'
mod 'grahamgilbert/macdefaults'
mod 'mosen/cups'
mod 'glarizza/pick'
mod 'puppetlabs/stdlib'
mod 'grahamgilbert/wan_ip'
mod 'grahamgilbert/crypt'
mod 'dhoppe/hosts'