forge "http://forge.puppetlabs.com"

# mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'

mod 'mac_admin', :git => "https://github.com/grahamgilbert/puppet-mac_admin.git"
mod 'mac_facts', :git => "https://github.com/grahamgilbert/grahamgilbert-mac_facts.git"
mod 'rcoleman/mac_profiles_handler'
mod 'grahamgilbert/macdefaults'
mod 'mosen/cups'
mod 'glarizza/pick'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/puppetdb'
mod 'grahamgilbert/wan_ip'
mod 'puppetlabs/apt'
mod 'puppetlabs/firewall'
mod 'puppetlabs/mysql'
mod 'puppetlabs/postgresql'
mod 'dashboard', :git => 'https://github.com/grahamgilbert/puppetlabs-dashboard.git'
mod 'puppetmaster', :git => 'https://github.com/fsalum/puppet-puppetmaster.git'
mod 'dhoppe/hosts'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/apache'
mod 'puppetlabs/ruby'
mod 'puppetlabs/passenger'
mod 'upstart', :git => "https://github.com/bison/puppet-upstart.git"