#!/bin/sh
#* Localiser
#+ chris.gerke@gmail.com
#+
#+ Description: Payload free. Localise Mac OS X System, current users and future users.
#+
#+ Version: 1.1
#+
#+ History:
#+     1.0: Script.
#+
#+ TODO:
#+     * Add more error checking?
#+     * Figure out geo position STUPID! This should be a dynamic script.
#+     * What to do for countries requiring multiple keyboard inputs (Canada etc). Make it elegant.

#+ See https://developer.apple.com for specifics, I'm only summarising here.

ME=$0
SCRIPT_DIR="$1/Contents/Resources"
TARGET_DIR="$3"

LANGUAGE="en"
LOCALE="en_GB"
COUNTRY=$(/bin/echo "${LOCALE}" | cut -d '_' -f 2)
#MEASUREMENTUNITS=$(/usr/bin/defaults read "${SCRIPT_DIR}/config" MEASUREMENTUNITS)
#METRICUNITS=$(/usr/bin/defaults read "${SCRIPT_DIR}/config" METRICUNITS)
LAYOUTID="2"
LAYOUTNAME="British"
TIMEZONE="Europe/London"

##exit if the touchfile exists
if [ -e "/Users/Shared/.localiserRun" ]
then
	/bin/echo "This has already run"
	exit 0
fi

#+ Set the language first, beware as languagesetup kills /Library/Preferences/.GlobalPreferences.plist
sudo /usr/sbin/languagesetup -langspec "${LANGUAGE}"

#+ Locale
sudo /usr/bin/defaults write /Library/Preferences/.GlobalPreferences AppleLocale -string "${LOCALE}"

#+ Country
sudo /usr/bin/defaults write /Library/Preferences/.GlobalPreferences Country -string "${COUNTRY}"

#+ Measurement Units (test this, maybe redundant with Lion)
#sudo /usr/bin/defaults write /Library/Preferences/.GlobalPreferences AppleMeasurementUnits -string "${MEASUREMENTUNITS}"

#+ Metric Units (test this, maybe redundant with Lion)
#sudo /usr/bin/defaults write /Library/Preferences/.GlobalPreferences AppleMetricUnits -string "${METRICUNITS}"

#+ System Keyboard Input
sudo /usr/libexec/PlistBuddy -c "Add :AppleCurrentKeyboardLayoutInputSourceID string com.apple.keylayout.${LAYOUTNAME}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleCurrentKeyboardLayoutInputSourceID com.apple.keylayout.${LAYOUTNAME}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Delete :AppleDefaultAsciiInputSource" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleDefaultAsciiInputSource:InputSourceKind string Keyboard\ Layout" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleDefaultAsciiInputSource:InputSourceKind Keyboard\ Layout" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleDefaultAsciiInputSource:KeyboardLayout\ ID integer ${LAYOUTID}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleDefaultAsciiInputSource:KeyboardLayout\ ID ${LAYOUTID}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleDefaultAsciiInputSource:KeyboardLayout\ Name string ${LAYOUTNAME}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleDefaultAsciiInputSource:KeyboardLayout\ Name ${LAYOUTNAME}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Delete :AppleEnabledInputSources" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleEnabledInputSources:0 dict" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleEnabledInputSources:0:InputSourceKind string Keyboard\ Layout" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleEnabledInputSources:0:InputSourceKind Keyboard\ Layout" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleEnabledInputSources:0:KeyboardLayout\ ID integer ${LAYOUTID}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleEnabledInputSources:0:KeyboardLayout\ ID ${LAYOUTID}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleEnabledInputSources:0:KeyboardLayout\ Name string ${LAYOUTNAME}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleEnabledInputSources:0:KeyboardLayout\ Name ${LAYOUTNAME}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Delete :AppleSelectedInputSources" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleSelectedInputSources:0 dict" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleSelectedInputSources:0:InputSourceKind string Keyboard\ Layout" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleSelectedInputSources:0:InputSourceKind Keyboard\ Layout" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleSelectedInputSources:0:KeyboardLayout\ ID integer ${LAYOUTID}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleSelectedInputSources:0:KeyboardLayout\ ID ${LAYOUTID}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Add :AppleSelectedInputSources:0:KeyboardLayout\ Name string ${LAYOUTNAME}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleSelectedInputSources:0:KeyboardLayout\ Name ${LAYOUTNAME}" "/Library/Preferences/com.apple.HIToolbox.plist"
sudo chown root:admin "/Library/Preferences/com.apple.HIToolbox.plist"
sudo chmod 644 "/Library/Preferences/com.apple.HIToolbox.plist"

#+ LoginWindow Keyboard Input
sudo /usr/libexec/PlistBuddy -c "Add :AppleCurrentKeyboardLayoutInputSourceID string com.apple.keylayout.${LAYOUTNAME}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :AppleCurrentKeyboardLayoutInputSourceID com.apple.keylayout.${LAYOUTNAME}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox dict" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Delete :com.apple.HIToolbox:AppleDefaultAsciiInputSource" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleDefaultAsciiInputSource array" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleDefaultAsciiInputSource:InputSourceKind string Keyboard\ Layout" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleDefaultAsciiInputSource:InputSourceKind Keyboard\ Layout" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleDefaultAsciiInputSource:KeyboardLayout\ ID integer ${LAYOUTID}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleDefaultAsciiInputSource:KeyboardLayout\ ID ${LAYOUTID}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleDefaultAsciiInputSource:KeyboardLayout\ Name string ${LAYOUTNAME}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleDefaultAsciiInputSource:KeyboardLayout\ Name ${LAYOUTNAME}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Delete :com.apple.HIToolbox:AppleEnabledInputSources" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleEnabledInputSources array" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleEnabledInputSources:0 dict" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleEnabledInputSources:0:InputSourceKind string Keyboard\ Layout" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleEnabledInputSources:0:InputSourceKind Keyboard\ Layout" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleEnabledInputSources:0:KeyboardLayout\ ID integer ${LAYOUTID}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleEnabledInputSources:0:KeyboardLayout\ ID ${LAYOUTID}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleEnabledInputSources:0:KeyboardLayout\ Name string ${LAYOUTNAME}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleEnabledInputSources:0:KeyboardLayout\ Name ${LAYOUTNAME}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Delete :com.apple.HIToolbox:AppleSelectedInputSources" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleSelectedInputSources array" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleSelectedInputSources:0 dict" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleSelectedInputSources:0:InputSourceKind string Keyboard\ Layout" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleSelectedInputSources:0:InputSourceKind Keyboard\ Layout" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleSelectedInputSources:0:KeyboardLayout\ ID integer ${LAYOUTID}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleSelectedInputSources:0:KeyboardLayout\ ID ${LAYOUTID}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Add :com.apple.HIToolbox:AppleSelectedInputSources:0:KeyboardLayout\ Name string ${LAYOUTNAME}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo /usr/libexec/PlistBuddy -c "Set :com.apple.HIToolbox:AppleSelectedInputSources:0:KeyboardLayout\ Name ${LAYOUTNAME}" "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
#+ Special Explicit Permissions!!!
sudo chown securityagent:wheel "/var/tmp/com.apple.HIToolbox.loginwindow.plist"
sudo chmod 644 "/var/tmp/com.apple.HIToolbox.loginwindow.plist"

#+ Loginwindow Keyboard Input Menu visibility
#+ FYI - I had issues with some Eastern European countries in 10.6.x when setting showInputMenu to TRUE. Loginwindow would hang.
sudo defaults write /Library/Preferences/com.apple.loginwindow showInputMenu -bool "TRUE"
sudo defaults write /var/ard/Library/Preferences/com.apple.menuextra.textinput ModeNameVisible -bool "TRUE"
sudo chmod 777 /Library/Preferences/com.apple.loginwindow.plist

#+ Timezone.
#sudo /usr/sbin/systemsetup -settimezone "${TIMEZONE}"
#All done, touch the file
sudo touch /Users/Shared/.localiserRun
exit 0

#####################################################################################################################################
# WORK IN PROGRESS, THE GOAL IS TO FIGURE OUT APPLE'S CURRENT LOCATION FRAMEWORK AND LOCALISE USING GEO POSITIONING
####################################################################################################################################
case ${LOCALE} in
Australia)
  LOCALE="en_AU"
  LANGUAGE="English"
  ;;
Tokyo)
  LOCALE="jp_JP"
  ;;
French)
  LOCALE="fr_FR"
  ;;
German)
  LOCALE="de_DE"
  ;;
Spanish)
  /bin/echo "${LOCALE}"
  ;;
Italian)
  /bin/echo "${LOCALE}"
  ;;
Portuguese)
  LANGUAGE="pt"
  LOCALE="pt_PT"
  ;;
Dutch)
  /bin/echo "${LOCALE}"
  ;;
Swedish)
  LANGUAGE="sv"
  ;;
Norwegian)
  LANGUAGE="no"
  ;;
Danish)
  LANGUAGE="da"
  ;;
Finnish)
  LANGUAGE="fi"
  LOCAL="fi_FI"
  ;;
Chinese)
  LANGUAGE="zh_CN"
  ;;
Taiwan)
  LANGUAGE="zh_TW"
  ;;
Korean)
  LANGUAGE="ko"
  ;;
*)
  /bin/echo "Using default."
  ;;
esac

/bin/echo "${LANGUAGE}"
/bin/echo "${LOCALE}"



exit 0